### ISSUE TITLE
No API docs

### ISSUE THREAD

**Issue by Kleidukos** [haskell-works/hw-balancedparens#123]
The README points to the [Hackage page](https://hackage.haskell.org/package/hw-balancedparens) but no docs are available.

![image](https://user-images.githubusercontent.com/29253044/80279037-46be2080-86fb-11ea-861e-b3425f32d443.png)

**Comment by newhoggy** [comment]
Usually that happens immediately after a new release because I don't build and upload the docs myself and rely on hackage to do it for me, which usually happens within a day or so.

**Comment by Kleidukos** [comment]
Hi, thank you very much!
